[package]
name = "mruby-gems"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies.artichoke-backend]
path = "../artichoke-backend"

[dependencies.rust-embed]
version = "4.5.0"
features = ["interpolate-folder-path"]
