[workspace]
members = [
  "artichoke-backend",
  "artichoke-core",
  "artichoke-frontend",
  "artichoke-vfs",
  "diamond",
  "diamond-rs",
  "mruby-sys",
  "spec-runner",
  "wasm",
]

[profile.release]
debug = true
lto = true
