[workspace]
members = [
  "artichoke-backend",
  "artichoke-core",
  "artichoke-frontend",
  "artichoke-vfs",
  "artichoke-wasm",
  "mruby-sys",
  "spec-runner",
]

[profile.release]
debug = true
lto = true
