[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "warn"
ignore = [
  # time/chrono problems, have not been a problem in practice
  # see: https://github.com/chronotope/chrono/issues/499
  "RUSTSEC-2020-0159",
]

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSL-1.0",
  "MIT",
]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
allow = []
deny = [
  { name = "time", version = ">=0.2.0" },
]
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
# allow-git = ["https://github.com/artichoke/rust-onig"]
