[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
highlight = "all"
allow = []
deny = []
skip = [
  { name = "proc-macro2", version = "<1.0" }, # version-check 0.8.1
  { name = "quote", version = "<1.0" }, # version-check 0.8.1
  { name = "syn", version = "<1.0" }, # version-check 0.8.1
  { name = "unicode-xid", version = "<1.0" }, # version-check 0.8.1
  { name = "version_check", version = "< 0.9" },
]
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/artichoke/rust-onig"]
