[package]
name = "mruby-rack"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies.mruby]
path = "../mruby"

[dependencies.rust-embed]
version = "4.3.0"
features = ["debug-embed"]
