[package]
name = "spinoso-array"
version = "0.3.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = """
Growable vector backends for the Ruby Array core type in Artichoke Ruby
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["array", "no_std", "spinoso", "vec", "vector"]
categories = ["data-structures", "no-std"]

[dependencies]
smallvec = { version = "1.4.1", optional = true }

[features]
default = ["small-array"]
# Add a `SmallArray` backend that implements the small vector optimization with
# the `smallvec` crate.
small-array = ["smallvec"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
