[package]
name = "mruby-sys"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[lib]
doctest = false

[dependencies]

[build-dependencies]
bindgen = "0.42.2"
cc = "1.0"
