[package]
name = "artichoke-frontend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rustyline = "5.0.2"

[dependencies.artichoke-backend]
path = "../artichoke-backend"

[dependencies.artichoke-core]
path = "../artichoke-core"
