[package]
name = "artichoke-core"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Core traits for implementing an Artichoke Ruby interpreter"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby"]
categories = ["data-structures", "rust-patterns"]

[dependencies]

[dev-dependencies]
doc-comment = "0.3"
