AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - stdlib/spec/**/*.rb
    - test/mspec.rb
    - test/mspec/**/*.rb
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
