AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - stdlib/uri.rb
    - stdlib/uri/*.rb
    - test/mspec.rb
    - test/mspec/**/*.rb
    - test/ruby-spec/**/*.rb
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
