[package]
name = "spinoso-random"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = """
Implementation of Ruby Random Core class.
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["random", "rand", "rng", "mt", "spinoso"]
categories = ["algorithms", "no-std"]

[dependencies]
getrandom = { version = "0.2", default-features = false }
libm = "0.2"
rand = { version = "0.8", optional = true, default-features = false }
rand_core = { version = "0.6", optional = true, default-features = false }

[features]
default = ["random-rand", "rand-traits", "std"]
# Enables range sampling methods for the `rand()` function.
random-rand = ["rand"]
# Enables implementations of `RngCore` on `Random` and `Mt` types.
rand-traits = ["rand_core"]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
