[package]
name = "spinoso-math"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = """
Implementation of the Ruby Math module
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["libm", "math", "no_std", "spinoso"]
categories = ["algorithms", "no-std"]

[dependencies]
libm = { version = "0.2", optional = true }

[features]
default = ["full", "std"]
# Implement the full Ruby `Math` API by including external crates for missing
# `core` APIs.
full = ["libm"]
# By default, `spinoso-math` is `no_std`. This feature enables
# `std::error::Error` impls.
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
