[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "mruby", "ruby"]
categories = ["api-bindings"]

[dependencies]
artichoke-core = { version = "0.6", path = "../artichoke-core" }
bstr = { version = "0.2, >= 0.2.2", default-features = false, features = ["std"] }
intaglio = "1.2"
itoa = "0.4"
log = "0.4, >= 0.4.5"
once_cell = "1"
regex = "1"
scolapasta-string-escape = { version = "0.1", path = "../scolapasta-string-escape" }
spinoso-array = { version = "0.4", path = "../spinoso-array", default-features = false }
spinoso-env = { version = "0.1", path = "../spinoso-env", optional = true }
spinoso-exception = { version = "0.1", path = "../spinoso-exception" }
spinoso-math = { version = "0.1", path = "../spinoso-math", optional = true }
spinoso-random = { version = "0.1", path = "../spinoso-random", optional = true }
spinoso-regexp = { version = "0.1", path = "../spinoso-regexp", optional = true }
spinoso-securerandom = { version = "0.1", path = "../spinoso-securerandom", optional = true }
spinoso-symbol = { version = "0.1", path = "../spinoso-symbol" }
spinoso-time = { version = "0.1", path = "../spinoso-time", optional = true }

[dependencies.onig]
version = "6.1"
default-features = false
optional = true

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
quickcheck_macros = "0.9"

[build-dependencies]
bindgen = { version = "0.56.0", default-features = false, features = ["runtime"] }
cc = "1.0"
target-lexicon = "0.11.1"

[features]
default = [
  "core-env",
  "core-env-system",
  "core-math",
  "core-math-full",
  "core-random",
  "core-regexp",
  "core-regexp-oniguruma",
  "core-time",
  "stdlib-securerandom"
]
core-env = ["spinoso-env"]
core-env-system = ["core-env", "spinoso-env/system-env"]
core-math = ["spinoso-math"]
core-math-full = ["core-math", "spinoso-math/full"]
core-random = ["spinoso-random"]
core-regexp = ["spinoso-regexp"]
core-regexp-oniguruma = ["spinoso-regexp/oniguruma", "onig"]
core-time = ["spinoso-time"]
native-filesystem-access = []
output-strategy-capture = []
output-strategy-null = ["output-strategy-capture"]
stdlib-securerandom = ["spinoso-securerandom"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
