[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby"]

[dependencies]
base64 = { version = "0.12", optional = true }
bstr = { version = "0.2", default-features = false, features = ["std"] }
chrono = "0.4"
dtoa = "0.4"
hex = { version = "0.4", optional = true }
itoa = "0.4"
libm = { version = "0.2", optional = true }
log = "0.4"
once_cell = "1"
rand = { version = "0.7", optional = true }
rand_pcg = { version = "0.2", optional = true }
regex = "1"
smallvec = "1"
uuid = { version = "0.8", optional = true, features = ["v4"] }

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.onig]
git = "https://github.com/artichoke/rust-onig"
rev = "ec266cae185ef4119008ea0b4799b9abd7161436"
default-features = false
optional = true

[dev-dependencies]
doc-comment = "0.3"
libc = "0.2"
quickcheck = { version = "0.9", default-features = false }
quickcheck_macros = "0.9"

[build-dependencies]
bindgen = { version = "0.54.0", default-features = false, features = ["runtime"] }
cc = "1.0"
target-lexicon = "0.11.0"

[features]
default = [
  "core-env-system",
  "core-math-extra",
  "core-random",
  "core-regexp-oniguruma",
  "stdlib-securerandom"
]
core-env-system = []
core-math-extra = ["libm"]
core-random = ["rand", "rand_pcg"]
core-regexp-oniguruma = ["onig"]
native-filesystem-access = []
output-strategy-capture = []
output-strategy-null = ["output-strategy-capture"]
stdlib-securerandom = ["base64", "hex", "rand", "uuid"]
