[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby"]

[dependencies]
bstr = "0.2"
chrono = "0.4"
downcast = "0.10"
log = "0.4"
memchr = "2"
once_cell = "1"
regex = "1"
smallvec = "1"

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.onig]
git = "https://github.com/artichoke/rust-onig"
rev = "11bc679d45b6799df2866cb4c90e1d542c4ba4c0"

[dependencies.rand]
version = "0.7"
optional = true
features = ["small_rng"]

[dev-dependencies]
libc = "0.2"
quickcheck_macros = "0.9"

[dev-dependencies.quickcheck]
version = "0.9"
default-features = false

[build-dependencies]
chrono = "0.4"
fs_extra = "1.1.0"
num_cpus = "1"
rustc_version = "0.2.3"
target-lexicon = "0.10.0"
walkdir = "2"

[build-dependencies.bindgen]
version = "0.53.1"
default-features = false
features = ["runtime"]

[build-dependencies.cc]
version = "1.0"
features = ["parallel"]

[features]
default = ["artichoke-random", "artichoke-system-environ"]
artichoke-random = ["rand"]
artichoke-system-environ = []
