[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby"]

[dependencies]
backtrace = { version = "0.3", optional = true }
bstr = "0.2"
chrono = "0.4"
downcast = "0.10"
log = "0.4"
memchr = "2"
once_cell = "1"
onig = "5"
regex = "1"
smallvec = "1"

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.artichoke-vfs]
path = "../artichoke-vfs"

[dependencies.rand]
version = "0.7"
optional = true
features = ["small_rng"]

[dev-dependencies]
libc = "0.2"
quickcheck = "0.9"
quickcheck_macros = "0.9"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
chrono = "0.4"
fs_extra = "1.1.0"
num_cpus = "1"
rayon = "1.2"
rustc_version = "0.2.3"
target-lexicon = "0.10.0"
walkdir = "2"

[build-dependencies.bindgen]
version = "0.51.1"
default-features = false

[features]
default = ["artichoke-array", "artichoke-random", "artichoke-system-environ"]
artichoke-all-converters = []
artichoke-array = []
artichoke-debug = ["backtrace"]
artichoke-random = ["rand"]
artichoke-system-environ = []
