[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies]
log = "0.4"
regex = "1"

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.artichoke-vfs]
path = "../artichoke-vfs"

[dependencies.mruby-sys]
path = "../mruby-sys"

[dependencies.onig]
version = "5"
# git = "https://github.com/artichoke/rust-onig"
# branch = "wasm"

[dev-dependencies]
env_logger = "0.6.1"
libc = "0.2"
quickcheck = "0.9"
quickcheck_macros = "0.8"

[build-dependencies]
chrono = "0.4"
fs_extra = "1.1.0"
rayon = "1.1"
rustc_version = "0.2.3"
target-lexicon = "0.8.1"
