[package]
name = "spec-runner"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Binary for running Ruby Specs with Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby", "ruby-spec", "testing"]
categories = ["development-tools::testing"]

[dependencies.artichoke-backend]
path = "../artichoke-backend"

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.rust-embed]
version = "5.1.0"
features = ["interpolate-folder-path"]

[build-dependencies]
fs_extra = "1.1.0"
