[package]
name = "spec-runner"
version = "0.3.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Binary for running Ruby Specs with Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby", "ruby-spec", "testing"]
categories = ["development-tools::testing"]

[dependencies]
artichoke = { path = "..", default-features = false, features = ["backtrace", "kitchen-sink"] }
rust-embed = "5.7.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
termcolor = "1.1"
toml = { version = "0.5", default-features = false }

# `spec-runner` is a regression testing tool
# Remove it from the main artichoke workspace.
[workspace]
members = ["."]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
